### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by gedw99** [Tom5521/GZGoLauncher#7]
https://github.com/ZDoom/gzdoom/releases has darwin versions for Mac

We just need to modify the launcher a little bit to cater for Mac

**Comment by Tom5521** [comment]
You are correct, but I have a few difficulties with this:

- I have no way to test it, so it would be practically blind.
-  I have very little knowledge about that OS other than what I already got from the posix standards.

Anyway I will try, no doubt that the first implementations will be a bit broken, but if they work they will work.

**Comment by Tom5521** [comment]
In theory this is it, I would appreciate if you report the bugs you come across, since as I said before, I am working with respect to this practically without testing Mac specific things.

**Comment by gedw99** [comment]
got it. Yes I am on a Mac and will report bugs.

you can also run a MAC in GitHub workflow

**Comment by gedw99** [comment]
I saw a few addictions in the PR's for Mac.
Its probably the same as Linux but if you update the ReadMe also for Mac then I can follow them here and then make PR with adjustments that I find from my Mac.

Is that cool ?

**Comment by Tom5521** [comment]
I can update the readme to compile and install for mac

Although I will only be able to add the installation method with go install.

Since I don't know much about the macos package system

**Comment by gedw99** [comment]
All good. I will try it from this end on my Mac :)
